Avr8bit-emulator: src/bit_test.c File Reference
bit_test.c File Reference
#include "bit_test.h"
Functions
void lsl (uint8_t d, struct CORE *core)
void lsr (uint8_t d, struct CORE *core)
void rol (uint8_t d, struct CORE *core)
void ror (uint8_t d, struct CORE *core)
void asr (uint8_t d, struct CORE *core)
void swap (uint8_t d, struct CORE *core)
void sbi (uint8_t IO, uint8_t n, struct CORE *core)
void cbi (uint8_t IO, uint8_t n, struct CORE *core)
void bst (uint8_t d, uint8_t b, struct CORE *core)
void bld (uint8_t d, uint8_t b, struct CORE *core)
void bset (uint8_t s, struct CORE *core)
void bclr (uint8_t s, struct CORE *core)
void sec (struct CORE *core)
void clc (struct CORE *core)
void sen (struct CORE *core)
void cln (struct CORE *core)
void sez (struct CORE *core)
void clz (struct CORE *core)
void sei (struct CORE *core)
void cli (struct CORE *core)
void ses (struct CORE *core)
void cls (struct CORE *core)
void sev (struct CORE *core)
void clv (struct CORE *core)
void set (struct CORE *core)
void clt (struct CORE *core)
void seh (struct CORE *core)
void clh (struct CORE *core)
Function Documentation
asr()
void asr (uint8_t d, struct CORE * core)
Definition at line 80 of file bit_test.c.
{
    // Arithmetic Shift Right
    // r(0) loaded into C
    // Rd <- Rd >> 1
    // 1 cycle
    core->sreg.C = core->gp.R[d] & 0x01;
    core->gp.R[d] = (core->gp.R[d] & 0x80) | (core->gp.R[d] >> 1);
    // Update SREG
    update_sreg_N(core, core->gp.R[d] >> 7);
    update_sreg_V(core, core->sreg.N ^ core->sreg.C);
    update_sreg_S(core, sreg_S_compute_bool(core->sreg.N, core->sreg.V));
    update_sreg_Z(core, sreg_Z_compute_bool(core->gp.R[d]));
    inc_pc(core);
}
References SREG::C, CORE::gp, inc_pc(), SREG::N, GP::R, CORE::sreg, sreg_S_compute_bool(), sreg_Z_compute_bool(), update_sreg_N(), update_sreg_S(), update_sreg_V(), update_sreg_Z(), and SREG::V.
bclr()
void bclr (uint8_t s, struct CORE * core)
Definition at line 169 of file bit_test.c.
{
    // Bit Clear in SREG
    // S <- 0
    // 1 cycle
    core->sreg.sreg = core->sreg.sreg & ~(1 << s);
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), SREG::sreg, and CORE::sreg.
bld()
void bld (uint8_t d, uint8_t b, struct CORE * core)
Definition at line 145 of file bit_test.c.
{
    // Bit Load from T Flag to Register
    // Rd(b) <- T
    // 1 cycle
    core->gp.R[d] = (core->gp.R[d] & ~(1 << b)) | (core->sreg.T << b);
    // Update SREG
    // NONE
    inc_pc(core);
}
References CORE::gp, inc_pc(), GP::R, CORE::sreg, and SREG::T.
bset()
void bset (uint8_t s, struct CORE * core)
Definition at line 157 of file bit_test.c.
{
    // Bit Set in SREG
    // S <- 1
    // 1 cycle
    core->sreg.sreg = core->sreg.sreg | (1 << s);
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), SREG::sreg, and CORE::sreg.
bst()
void bst (uint8_t d, uint8_t b, struct CORE * core)
Definition at line 133 of file bit_test.c.
{
    // Bit Store from Register to T Flag
    // T <- Rd(b)
    // 1 cycle
    core->sreg.T = (core->gp.R[d] & (1 << b)) >> b;
    // Update SREG
    // T updated by instruction
    inc_pc(core);
}
References CORE::gp, inc_pc(), GP::R, CORE::sreg, and SREG::T.
cbi()
void cbi (uint8_t IO, uint8_t n, struct CORE * core)
Definition at line 121 of file bit_test.c.
{
    // Clear Bit in I/O Register
    // I/O(n) <- 0
    // 2 cycle
    core->gp.R[IO] = core->gp.R[IO] & ~(1 << n);
    // Update SREG
    // NONE
    inc_pc(core);
}
References CORE::gp, inc_pc(), and GP::R.
clc()
void clc (struct CORE * core)
Definition at line 193 of file bit_test.c.
{
    // Clear Cary Flag
    // C <- 0
    // 1 cycle
    core->sreg.C = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References SREG::C, inc_pc(), and CORE::sreg.
clh()
void clh (struct CORE * core)
Definition at line 361 of file bit_test.c.
{
    // Clear Half Cary Flag
    // H <- 0
    // 1 cycle
    core->sreg.H = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References SREG::H, inc_pc(), and CORE::sreg.
cli()
void cli (struct CORE * core)
Definition at line 265 of file bit_test.c.
{
    // Clear Global Interupt Enable
    // I <- 0
    // 1 cycle
    core->sreg.I = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References SREG::I, inc_pc(), and CORE::sreg.
cln()
void cln (struct CORE * core)
Definition at line 217 of file bit_test.c.
{
    // Clear Negative Flag
    // N <- 0
    // 1 cycle
    core->sreg.N = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), SREG::N, and CORE::sreg.
cls()
void cls (struct CORE * core)
Definition at line 289 of file bit_test.c.
{
    // Clear Signed Flag
    // S <- 0
    // 1 cycle
    core->sreg.S = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), SREG::S, and CORE::sreg.
clt()
void clt (struct CORE * core)
Definition at line 337 of file bit_test.c.
{
    // Clear T Flag
    // T <- 0
    // 1 cycle
    core->sreg.T = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), CORE::sreg, and SREG::T.
clv()
void clv (struct CORE * core)
Definition at line 313 of file bit_test.c.
{
    // Clear Two's complement overflow flag
    // V <- 0
    // 1 cycle
    core->sreg.V = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), CORE::sreg, and SREG::V.
clz()
void clz (struct CORE * core)
Definition at line 241 of file bit_test.c.
{
    // Clear Zero Flag
    // Z <- 0
    // 1 cycle
    core->sreg.Z = 0;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), CORE::sreg, and SREG::Z.
lsl()
void lsl (uint8_t d, struct CORE * core)
Definition at line 3 of file bit_test.c.
{
    // Logical Shift Left
    // r(7) loaded into C
    // Rd <- Rd << 1
    // 1 cycle
    core->sreg.C = (core->gp.R[d] & 0x80) >> 7;
    core->gp.R[d] = core->gp.R[d] << 1;
    // Update SREG
    // C updated by instruction
    update_sreg_H(core, (core->gp.R[d] & 0x0F) >> 3);
    update_sreg_N(core, core->gp.R[d] >> 7);
    update_sreg_V(core, core->sreg.N ^ core->sreg.C);
    update_sreg_S(core, sreg_S_compute_bool(core->sreg.N, core->sreg.V));
    update_sreg_Z(core, sreg_Z_compute_bool(core->gp.R[d]));
    inc_pc(core);
}
References SREG::C, CORE::gp, inc_pc(), SREG::N, GP::R, CORE::sreg, sreg_S_compute_bool(), sreg_Z_compute_bool(), update_sreg_H(), update_sreg_N(), update_sreg_S(), update_sreg_V(), update_sreg_Z(), and SREG::V.
lsr()
void lsr (uint8_t d, struct CORE * core)
Definition at line 23 of file bit_test.c.
{
    // Logical Shift Right
    // r(0) loaded into C
    // Rd <- Rd >> 1
    // 1 cycle
    core->sreg.C = core->gp.R[d] & 0x01;
    core->gp.R[d] = core->gp.R[d] >> 1;
    // Update SREG
    update_sreg_N(core, false);
    update_sreg_V(core, core->sreg.N ^ core->sreg.C);
    update_sreg_S(core, sreg_S_compute_bool(core->sreg.N, core->sreg.V));
    update_sreg_Z(core, sreg_Z_compute_bool(core->gp.R[d]));
    inc_pc(core);
}
References SREG::C, CORE::gp, inc_pc(), SREG::N, GP::R, CORE::sreg, sreg_S_compute_bool(), sreg_Z_compute_bool(), update_sreg_N(), update_sreg_S(), update_sreg_V(), update_sreg_Z(), and SREG::V.
rol()
void rol (uint8_t d, struct CORE * core)
Definition at line 41 of file bit_test.c.
{
    // Rotate Left through Cary
    // r(7) loaded into C
    // Rd <- Rd << 1 | C
    // 1 cycle
    bool temp = core->sreg.C;
    core->sreg.C = (core->gp.R[d] & 0x80) >> 7;
    core->gp.R[d] = (core->gp.R[d] << 1) | temp;
    // Update SREG
    // C updated by instruction
    update_sreg_H(core, (core->gp.R[d] & 0x0F) >> 3);
    update_sreg_N(core, core->gp.R[d] >> 7);
    update_sreg_V(core, core->sreg.N ^ core->sreg.C);
    update_sreg_S(core, sreg_S_compute_bool(core->sreg.N, core->sreg.V));
    update_sreg_Z(core, sreg_Z_compute_bool(core->gp.R[d]));
    inc_pc(core);
}
References SREG::C, CORE::gp, inc_pc(), SREG::N, GP::R, CORE::sreg, sreg_S_compute_bool(), sreg_Z_compute_bool(), update_sreg_H(), update_sreg_N(), update_sreg_S(), update_sreg_V(), update_sreg_Z(), and SREG::V.
ror()
void ror (uint8_t d, struct CORE * core)
Definition at line 61 of file bit_test.c.
{
    // Rotate Right through Cary
    // r(0) loaded into C
    // Rd <- Rd >> 1 | C << 7
    // 1 cycle
    bool temp = core->sreg.C;
    core->sreg.C = core->gp.R[d] & 0x01;
    core->gp.R[d] = (core->gp.R[d] >> 1) | (temp << 7);
    // Update SREG
    // C updated by instruction
    update_sreg_N(core, core->gp.R[d] >> 7);
    update_sreg_V(core, core->sreg.N ^ core->sreg.C);
    update_sreg_S(core, sreg_S_compute_bool(core->sreg.N, core->sreg.V));
    update_sreg_Z(core, sreg_Z_compute_bool(core->gp.R[d]));
    inc_pc(core);
}
References SREG::C, CORE::gp, inc_pc(), SREG::N, GP::R, CORE::sreg, sreg_S_compute_bool(), sreg_Z_compute_bool(), update_sreg_N(), update_sreg_S(), update_sreg_V(), update_sreg_Z(), and SREG::V.
sbi()
void sbi (uint8_t IO, uint8_t n, struct CORE * core)
Definition at line 109 of file bit_test.c.
{
    // Set Bit in I/O Register
    // I/O(n) <- 1
    // 2 cycle
    core->gp.R[IO] = core->gp.R[IO] | (1 << n);
    // Update SREG
    // NONE
    inc_pc(core);
}
References CORE::gp, inc_pc(), and GP::R.
sec()
void sec (struct CORE * core)
Definition at line 181 of file bit_test.c.
{
    // Set Cary Flag
    // C <- 1
    // 1 cycle
    core->sreg.C = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References SREG::C, inc_pc(), and CORE::sreg.
seh()
void seh (struct CORE * core)
Definition at line 349 of file bit_test.c.
{
    // Set Half Cary Flag
    // H <- 1
    // 1 cycle
    core->sreg.H = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References SREG::H, inc_pc(), and CORE::sreg.
sei()
void sei (struct CORE * core)
Definition at line 253 of file bit_test.c.
{
    // Set Global Interupt Enable
    // I <- 1
    // 1 cycle
    core->sreg.I = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References SREG::I, inc_pc(), and CORE::sreg.
sen()
void sen (struct CORE * core)
Definition at line 205 of file bit_test.c.
{
    // Set Negative Flag
    // N <- 1
    // 1 cycle
    core->sreg.N = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), SREG::N, and CORE::sreg.
ses()
void ses (struct CORE * core)
Definition at line 277 of file bit_test.c.
{
    // Set Signed Flag
    // S <- 1
    // 1 cycle
    core->sreg.S = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), SREG::S, and CORE::sreg.
set()
void set (struct CORE * core)
Definition at line 325 of file bit_test.c.
{
    // Set T Flag
    // T <- 1
    // 1 cycle
    core->sreg.T = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), CORE::sreg, and SREG::T.
sev()
void sev (struct CORE * core)
Definition at line 301 of file bit_test.c.
{
    // Set Two's complement overflow flag
    // V <- 1
    // 1 cycle
    core->sreg.V = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), CORE::sreg, and SREG::V.
sez()
void sez (struct CORE * core)
Definition at line 229 of file bit_test.c.
{
    // Set Zero Flag
    // Z <- 1
    // 1 cycle
    core->sreg.Z = 1;
    // Update SREG
    // Updated by instruction
    inc_pc(core);
}
References inc_pc(), CORE::sreg, and SREG::Z.
swap()
void swap (uint8_t d, struct CORE * core)
Definition at line 97 of file bit_test.c.
{
    // Swap Nibbles
    // Rd <- Rd(3:0) << 4 | Rd(7:4)
    // 1 cycle
    core->gp.R[d] = (core->gp.R[d] & 0x0F) << 4 | (core->gp.R[d] & 0xF0) >> 4;
    // Update SREG
    // NONE
    inc_pc(core);
}
References CORE::gp, inc_pc(), and GP::R.