Avr8bit-emulator: src/core.c File Reference
core.c File Reference
#include "core.h"
Functions
void inc_pc (struct CORE *core)
Function Documentation
inc_pc()
void inc_pc (struct CORE * core)
Definition at line 3 of file core.c.
{
    core->PC = core->PC + 1;
}
References CORE::PC.
Referenced by adc(), add(), adiw(), and(), andi(), asr(), bclr(), bld(), bset(), bst(), cbi(), cbr(), clc(), clh(), cli(), cln(), clr(), cls(), clt(), clv(), clz(), com(), dec(), eor(), fmul(), fmuls(), fmulsu(), in(), inc(), lac(), las(), lat(), ld_x(), ld_x_dec(), ld_x_inc(), ld_y(), ld_y_dec(), ld_y_inc(), ld_z(), ld_z_dec(), ld_z_inc(), ldd_y(), ldd_z(), ldi(), lds(), lpm_0(), lpm_z(), lpm_z_inc(), lsl(), lsr(), mov(), movw(), mul(), muls(), mulsu(), neg(), or(), ori(), out(), pop(), push(), rol(), ror(), sbc(), sbci(), sbi(), sbiw(), sbr(), sec(), seh(), sei(), sen(), ser(), ses(), set(), sev(), sez(), st_x(), st_x_dec(), st_x_inc(), st_y(), st_y_dec(), st_y_inc(), st_z(), st_z_dec(), st_z_inc(), std_y(), std_z(), sts(), sub(), subi(), swap(), tst(), and xch().