Avr8bit-emulator: include/sreg_utils.h File Reference
sreg_utils.h File Reference
Functions for manipulating the Status Register (SREG)
#include <stdint.h>
#include <stdbool.h>
#include "core.h"
Functions
bool sreg_H_compute_bool (uint8_t Rd, uint8_t Rr)
Computes the H flag as a boolean value.
bool sreg_Z_compute_bool (uint8_t result)
Computes the Z flag as a boolean value.
bool sreg_C_compute_bool (uint8_t Rd, uint8_t Rr)
Computes the C flag as a boolean value.
bool sreg_N_compute_bool (uint8_t result)
Computes the N flag as a boolean value.
bool sreg_V_compute_bool (uint8_t Rd, uint8_t Rr, uint8_t result)
Computes the V flag as a boolean value.
bool sreg_S_compute_bool (bool N, bool V)
Computes the S flag as a boolean value.
uint8_t sreg_C_compute (uint8_t Rd, uint8_t Rr)
Computes the C flag as an 8-bit value.
uint8_t sreg_Z_compute (uint8_t result)
Computes the Z flag as an 8-bit value.
uint8_t sreg_N_compute (uint8_t result)
Computes the N flag as an 8-bit value.
uint8_t sreg_V_compute (uint8_t Rd, uint8_t Rr, uint8_t result)
Computes the V flag as an 8-bit value.
uint8_t sreg_S_compute (bool N, bool V)
Computes the S flag as an 8-bit value.
uint8_t sreg_H_compute (uint8_t Rd, uint8_t Rr)
Computes the H flag as an 8-bit value.
void update_sreg_arithm (struct CORE *core, uint8_t Rd, uint8_t Rr, uint8_t result)
Updates the Status Register (SREG) for arithmetic operations.
void update_sreg_logic (struct CORE *core, uint8_t result)
Updates the Status Register (SREG) for logical operations.
void udpate_sreg_arithm_16bit (struct CORE *core, uint16_t Rd, uint16_t result)
Updates the Status Register (SREG) for 16-bit arithmetic operations.
void update_sreg_C (struct CORE *core, bool state)
Update the Carry flag (C) in the status register.
void update_sreg_Z (struct CORE *core, bool state)
Update the Zero flag (Z) in the status register.
void update_sreg_N (struct CORE *core, bool state)
Update the Negative flag (N) in the status register.
void update_sreg_V (struct CORE *core, bool state)
Update the Overflow flag (V) in the status register.
void update_sreg_S (struct CORE *core, bool state)
Update the Sign flag (S) in the status register.
void update_sreg_H (struct CORE *core, bool state)
Update the Half Carry flag (H) in the status register.
void update_sreg_T (struct CORE *core, bool state)
Update the Transfer bit (T) in the status register.
void update_sreg_I (struct CORE *core, bool state)
Update the Interrupt flag (I) in the status register.
Detailed Description
Functions for manipulating the Status Register (SREG)
Author
Antonin Pivard
Date
2024
Warning
Not tested
Copyright
GNU General Public License v3.0
Definition in file sreg_utils.h.
Function Documentation
sreg_C_compute()
uint8_t sreg_C_compute (uint8_t Rd, uint8_t Rr)
Computes the C flag as an 8-bit value.
Parameters
Rd The value of the destination register.
Rr The value of the source register.
Returns
The computed C flag.
Definition at line 27 of file sreg_utils.c.
{
    return ((uint16_t)Rd + (uint16_t)Rr > 0xFF);
}
Referenced by update_sreg_arithm().
sreg_C_compute_bool()
bool sreg_C_compute_bool (uint8_t Rd, uint8_t Rr)
Computes the C flag as a boolean value.
Parameters
Rd The value of the destination register.
Rr The value of the source register.
Returns
true if the C flag should be set, false otherwise.
Definition at line 11 of file sreg_utils.c.
{
    return ((uint16_t)Rd + (uint16_t)Rr > 0xFF);
}
sreg_H_compute()
uint8_t sreg_H_compute (uint8_t Rd, uint8_t Rr)
Computes the H flag as an 8-bit value.
Parameters
Rd The value of the destination register.
Rr The value of the source register.
Returns
The computed H flag.
Definition at line 47 of file sreg_utils.c.
{
    return ((Rd & 0x0F) + (Rr & 0x0F) > 0x0F ? 32 : 0);
}
Referenced by update_sreg_arithm().
sreg_H_compute_bool()
bool sreg_H_compute_bool (uint8_t Rd, uint8_t Rr)
Computes the H flag as a boolean value.
Parameters
Rd The value of the destination register.
Rr The value of the source register.
Returns
true if the H flag should be set, false otherwise.
Definition at line 3 of file sreg_utils.c.
{
    return ((Rd & 0x0F) + (Rr & 0x0F) > 0x0F);
}
sreg_N_compute()
uint8_t sreg_N_compute (uint8_t result)
Computes the N flag as an 8-bit value.
Parameters
result The result of the operation.
Returns
The computed N flag.
Definition at line 35 of file sreg_utils.c.
{
    return (result & 0x80 ? 4 : 0);
}
Referenced by update_sreg_arithm(), and update_sreg_logic().
sreg_N_compute_bool()
bool sreg_N_compute_bool (uint8_t result)
Computes the N flag as a boolean value.
Parameters
result The result of the operation.
Returns
true if the N flag should be set, false otherwise.
Definition at line 15 of file sreg_utils.c.
{
    return (result & 0x80);
}
sreg_S_compute()
uint8_t sreg_S_compute (bool N, bool V)
Computes the S flag as an 8-bit value.
Parameters
N The value of the N flag.
V The value of the V flag.
Returns
The computed S flag.
Definition at line 43 of file sreg_utils.c.
{
    return (N ^ V ? 16 : 0);
}
Referenced by udpate_sreg_arithm_16bit(), update_sreg_arithm(), and update_sreg_logic().
sreg_S_compute_bool()
bool sreg_S_compute_bool (bool N, bool V)
Computes the S flag as a boolean value.
Parameters
N The value of the N flag.
V The value of the V flag.
Returns
true if the S flag should be set, false otherwise.
Definition at line 23 of file sreg_utils.c.
{
    return (N ^ V);
}
Referenced by asr(), lsl(), lsr(), rol(), and ror().
sreg_V_compute()
uint8_t sreg_V_compute (uint8_t Rd, uint8_t Rr, uint8_t result)
Computes the V flag as an 8-bit value.
Parameters
Rd The value of the destination register.
Rr The value of the source register.
result The result of the operation.
Returns
The computed V flag.
Definition at line 39 of file sreg_utils.c.
{
    return ((Rd & Rr & ~result) | (~Rd & ~Rr & result) ? 8 : 0);
}
Referenced by update_sreg_arithm().
sreg_V_compute_bool()
bool sreg_V_compute_bool (uint8_t Rd, uint8_t Rr, uint8_t result)
Computes the V flag as a boolean value.
Parameters
Rd The value of the destination register.
Rr The value of the source register.
result The result of the operation.
Returns
true if the V flag should be set, false otherwise.
Definition at line 19 of file sreg_utils.c.
{
    return ((Rd & Rr & ~result) | (~Rd & ~Rr & result));
}
sreg_Z_compute()
uint8_t sreg_Z_compute (uint8_t result)
Computes the Z flag as an 8-bit value.
Parameters
result The result of the operation.
Returns
The computed Z flag.
Definition at line 31 of file sreg_utils.c.
{
    return (result == 0 ? 2 : 0);
}
Referenced by update_sreg_arithm(), and update_sreg_logic().
sreg_Z_compute_bool()
bool sreg_Z_compute_bool (uint8_t result)
Computes the Z flag as a boolean value.
Parameters
result The result of the operation.
Returns
true if the Z flag should be set, false otherwise.
Definition at line 7 of file sreg_utils.c.
{
    return (result == 0);
}
Referenced by asr(), lsl(), lsr(), rol(), and ror().
udpate_sreg_arithm_16bit()
void udpate_sreg_arithm_16bit (struct CORE * core, uint16_t Rd, uint16_t result)
Updates the Status Register (SREG) for 16-bit arithmetic operations.
This function updates the SREG based on the result of a 16-bit arithmetic operation.
Parameters
core Pointer to the CORE structure.
Rd The destination register value.
result The result of the 16-bit arithmetic operation.
Definition at line 67 of file sreg_utils.c.
{
    core->sreg.C = (!(Rd>>15) & (result>>15));
    core->sreg.Z = result == 0 ? 1 : 0;
    core->sreg.N = result >> 15;
    core->sreg.V = (!(Rd>>15) & (result>>15));
    core->sreg.S = sreg_S_compute(core->sreg.N, core->sreg.V);
}
References SREG::C, SREG::N, SREG::S, CORE::sreg, sreg_S_compute(), SREG::V, and SREG::Z.
Referenced by adiw(), and sbiw().
update_sreg_arithm()
void update_sreg_arithm (struct CORE * core, uint8_t Rd, uint8_t Rr, uint8_t result)
Updates the Status Register (SREG) for arithmetic operations.
This function updates the SREG based on the result of an arithmetic operation.
Parameters
core Pointer to the CORE structure.
Rd The destination register value.
Rr The source register value.
result The result of the arithmetic operation.
Definition at line 51 of file sreg_utils.c.
{
    core->sreg.C = sreg_C_compute(Rd, Rr);
    core->sreg.Z = sreg_Z_compute(result);
    core->sreg.N = sreg_N_compute(result);
    core->sreg.V = sreg_V_compute(Rd, Rr, result);
    core->sreg.S = sreg_S_compute(core->sreg.N, core->sreg.V);
    core->sreg.H = sreg_H_compute(Rd, Rr);
}
References SREG::C, SREG::H, SREG::N, SREG::S, CORE::sreg, sreg_C_compute(), sreg_H_compute(), sreg_N_compute(), sreg_S_compute(), sreg_V_compute(), sreg_Z_compute(), SREG::V, and SREG::Z.
Referenced by adc(), add(), cp(), cpc(), cpi(), sbc(), sbci(), sub(), and subi().
update_sreg_C()
void update_sreg_C (struct CORE * core, bool state)
Update the Carry flag (C) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Carry flag.
Definition at line 75 of file sreg_utils.c.
{
    core->sreg.C = state;
}
References SREG::C, and CORE::sreg.
Referenced by com().
update_sreg_H()
void update_sreg_H (struct CORE * core, bool state)
Update the Half Carry flag (H) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Half Carry flag.
Definition at line 95 of file sreg_utils.c.
{
    core->sreg.H = state;
}
References SREG::H, and CORE::sreg.
Referenced by lsl(), and rol().
update_sreg_I()
void update_sreg_I (struct CORE * core, bool state)
Update the Interrupt flag (I) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Interrupt flag.
Definition at line 103 of file sreg_utils.c.
{
    core->sreg.I = state;
}
References SREG::I, and CORE::sreg.
Referenced by reti().
update_sreg_logic()
void update_sreg_logic (struct CORE * core, uint8_t result)
Updates the Status Register (SREG) for logical operations.
This function updates the SREG based on the result of a logical operation.
Parameters
core Pointer to the CORE structure.
result The result of the logical operation.
Definition at line 60 of file sreg_utils.c.
{
    core->sreg.Z = sreg_Z_compute(result);
    core->sreg.N = sreg_N_compute(result);
    core->sreg.V = 0;
    core->sreg.S = sreg_S_compute(core->sreg.N, core->sreg.V);
}
References SREG::N, SREG::S, CORE::sreg, sreg_N_compute(), sreg_S_compute(), sreg_Z_compute(), SREG::V, and SREG::Z.
Referenced by and(), andi(), com(), eor(), or(), and ori().
update_sreg_N()
void update_sreg_N (struct CORE * core, bool state)
Update the Negative flag (N) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Negative flag.
Definition at line 83 of file sreg_utils.c.
{
    core->sreg.N = state;
}
References SREG::N, and CORE::sreg.
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_S()
void update_sreg_S (struct CORE * core, bool state)
Update the Sign flag (S) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Sign flag.
Definition at line 91 of file sreg_utils.c.
{
    core->sreg.S = state;
}
References SREG::S, and CORE::sreg.
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_T()
void update_sreg_T (struct CORE * core, bool state)
Update the Transfer bit (T) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Transfer bit.
Definition at line 99 of file sreg_utils.c.
{
    core->sreg.T = state;
}
References CORE::sreg, and SREG::T.
update_sreg_V()
void update_sreg_V (struct CORE * core, bool state)
Update the Overflow flag (V) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Overflow flag.
Definition at line 87 of file sreg_utils.c.
{
    core->sreg.V = state;
}
References CORE::sreg, and SREG::V.
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_Z()
void update_sreg_Z (struct CORE * core, bool state)
Update the Zero flag (Z) in the status register.
Parameters
core Pointer to the CORE structure.
state Boolean state to set the Zero flag.
Definition at line 79 of file sreg_utils.c.
{
    core->sreg.Z = state;
}
References CORE::sreg, and SREG::Z.
Referenced by asr(), lsl(), lsr(), rol(), and ror().