Avr8bit-emulator: src/sreg_utils.c File Reference
sreg_utils.c File Reference
#include "sreg_utils.h"
Functions
bool sreg_H_compute_bool (uint8_t Rd, uint8_t Rr)
bool sreg_Z_compute_bool (uint8_t result)
bool sreg_C_compute_bool (uint8_t Rd, uint8_t Rr)
bool sreg_N_compute_bool (uint8_t result)
bool sreg_V_compute_bool (uint8_t Rd, uint8_t Rr, uint8_t result)
bool sreg_S_compute_bool (bool N, bool V)
uint8_t sreg_C_compute (uint8_t Rd, uint8_t Rr)
uint8_t sreg_Z_compute (uint8_t result)
uint8_t sreg_N_compute (uint8_t result)
uint8_t sreg_V_compute (uint8_t Rd, uint8_t Rr, uint8_t result)
uint8_t sreg_S_compute (bool N, bool V)
uint8_t sreg_H_compute (uint8_t Rd, uint8_t Rr)
void update_sreg_arithm (struct CORE *core, uint8_t Rd, uint8_t Rr, uint8_t result)
void update_sreg_logic (struct CORE *core, uint8_t result)
void update_sreg_C (struct CORE *core, bool state)
void update_sreg_Z (struct CORE *core, bool state)
void update_sreg_N (struct CORE *core, bool state)
void update_sreg_V (struct CORE *core, bool state)
void update_sreg_S (struct CORE *core, bool state)
void update_sreg_H (struct CORE *core, bool state)
void update_sreg_T (struct CORE *core, bool state)
void update_sreg_I (struct CORE *core, bool state)
Function Documentation
sreg_C_compute()
uint8_t sreg_C_compute (uint8_t Rd, uint8_t Rr)
Definition at line 27 of file sreg_utils.c.
{
    return ((uint16_t)Rd + (uint16_t)Rr > 0xFF);
}
Referenced by update_sreg_arithm().
sreg_C_compute_bool()
bool sreg_C_compute_bool (uint8_t Rd, uint8_t Rr)
Definition at line 11 of file sreg_utils.c.
{
    return ((uint16_t)Rd + (uint16_t)Rr > 0xFF);
}
sreg_H_compute()
uint8_t sreg_H_compute (uint8_t Rd, uint8_t Rr)
Definition at line 47 of file sreg_utils.c.
{
    return ((Rd & 0x0F) + (Rr & 0x0F) > 0x0F ? 32 : 0);
}
Referenced by update_sreg_arithm().
sreg_H_compute_bool()
bool sreg_H_compute_bool (uint8_t Rd, uint8_t Rr)
Definition at line 3 of file sreg_utils.c.
{
    return ((Rd & 0x0F) + (Rr & 0x0F) > 0x0F);
}
sreg_N_compute()
uint8_t sreg_N_compute (uint8_t result)
Definition at line 35 of file sreg_utils.c.
{
    return (result & 0x80 ? 4 : 0);
}
Referenced by update_sreg_arithm(), and update_sreg_logic().
sreg_N_compute_bool()
bool sreg_N_compute_bool (uint8_t result)
Definition at line 15 of file sreg_utils.c.
{
    return (result & 0x80);
}
sreg_S_compute()
uint8_t sreg_S_compute (bool N, bool V)
Definition at line 43 of file sreg_utils.c.
{
    return (N ^ V ? 16 : 0);
}
Referenced by update_sreg_arithm(), and update_sreg_logic().
sreg_S_compute_bool()
bool sreg_S_compute_bool (bool N, bool V)
Definition at line 23 of file sreg_utils.c.
{
    return (N ^ V);
}
Referenced by asr(), lsl(), lsr(), rol(), and ror().
sreg_V_compute()
uint8_t sreg_V_compute (uint8_t Rd, uint8_t Rr, uint8_t result)
Definition at line 39 of file sreg_utils.c.
{
    return ((Rd & Rr & ~result) | (~Rd & ~Rr & result) ? 8 : 0);
}
Referenced by update_sreg_arithm().
sreg_V_compute_bool()
bool sreg_V_compute_bool (uint8_t Rd, uint8_t Rr, uint8_t result)
Definition at line 19 of file sreg_utils.c.
{
    return ((Rd & Rr & ~result) | (~Rd & ~Rr & result));
}
sreg_Z_compute()
uint8_t sreg_Z_compute (uint8_t result)
Definition at line 31 of file sreg_utils.c.
{
    return (result == 0 ? 2 : 0);
}
Referenced by update_sreg_arithm(), and update_sreg_logic().
sreg_Z_compute_bool()
bool sreg_Z_compute_bool (uint8_t result)
Definition at line 7 of file sreg_utils.c.
{
    return (result == 0);
}
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_arithm()
void update_sreg_arithm (struct CORE * core, uint8_t Rd, uint8_t Rr, uint8_t result)
Definition at line 51 of file sreg_utils.c.
{
    core->sreg.C = sreg_C_compute(Rd, Rr);
    core->sreg.Z = sreg_Z_compute(result);
    core->sreg.N = sreg_N_compute(result);
    core->sreg.V = sreg_V_compute(Rd, Rr, result);
    core->sreg.S = sreg_S_compute(core->sreg.N, core->sreg.V);
    core->sreg.H = sreg_H_compute(Rd, Rr);
}
References SREG::C, SREG::H, SREG::N, SREG::S, CORE::sreg, sreg_C_compute(), sreg_H_compute(), sreg_N_compute(), sreg_S_compute(), sreg_V_compute(), sreg_Z_compute(), SREG::V, and SREG::Z.
Referenced by adc(), add(), cp(), cpc(), cpi(), sbc(), sbci(), sub(), and subi().
update_sreg_C()
void update_sreg_C (struct CORE * core, bool state)
Definition at line 67 of file sreg_utils.c.
{
    core->sreg.C = state;
}
References SREG::C, and CORE::sreg.
Referenced by com().
update_sreg_H()
void update_sreg_H (struct CORE * core, bool state)
Definition at line 87 of file sreg_utils.c.
{
    core->sreg.H = state;
}
References SREG::H, and CORE::sreg.
Referenced by lsl(), and rol().
update_sreg_I()
void update_sreg_I (struct CORE * core, bool state)
Definition at line 95 of file sreg_utils.c.
{
    core->sreg.I = state;
}
References SREG::I, and CORE::sreg.
Referenced by reti().
update_sreg_logic()
void update_sreg_logic (struct CORE * core, uint8_t result)
Definition at line 60 of file sreg_utils.c.
{
    core->sreg.Z = sreg_Z_compute(result);
    core->sreg.N = sreg_N_compute(result);
    core->sreg.V = 0;
    core->sreg.S = sreg_S_compute(core->sreg.N, core->sreg.V);
}
References SREG::N, SREG::S, CORE::sreg, sreg_N_compute(), sreg_S_compute(), sreg_Z_compute(), SREG::V, and SREG::Z.
Referenced by and(), andi(), com(), eor(), or(), and ori().
update_sreg_N()
void update_sreg_N (struct CORE * core, bool state)
Definition at line 75 of file sreg_utils.c.
{
    core->sreg.N = state;
}
References SREG::N, and CORE::sreg.
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_S()
void update_sreg_S (struct CORE * core, bool state)
Definition at line 83 of file sreg_utils.c.
{
    core->sreg.S = state;
}
References SREG::S, and CORE::sreg.
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_T()
void update_sreg_T (struct CORE * core, bool state)
Definition at line 91 of file sreg_utils.c.
{
    core->sreg.T = state;
}
References CORE::sreg, and SREG::T.
update_sreg_V()
void update_sreg_V (struct CORE * core, bool state)
Definition at line 79 of file sreg_utils.c.
{
    core->sreg.V = state;
}
References CORE::sreg, and SREG::V.
Referenced by asr(), lsl(), lsr(), rol(), and ror().
update_sreg_Z()
void update_sreg_Z (struct CORE * core, bool state)
Definition at line 71 of file sreg_utils.c.
{
    core->sreg.Z = state;
}
References CORE::sreg, and SREG::Z.
Referenced by asr(), lsl(), lsr(), rol(), and ror().